version: '3.9'

networks:
  backend:
    name: songs-local-server-sls-backend-network
volumes:
  aws-data:

services:
  aws:
    container_name: songs-local-server-sls-aws
    image: localstack/localstack-full:0.13.3
    ports:
      - 4566:4566
    environment:
      - SERVICES=dynamodb,s3
      - EDGE_PORT=4566
      - DATA_DIR=/tmp/localstack/data
      - DYNAMODB_SHARE_DB=1
    volumes:
      - type: volume
        source: aws-data
        target: /tmp/localstack/data
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
    networks:
      - backend

  watcher:
    container_name: songs-local-server-sls-watcher
    build:
      dockerfile: watcher.dockerfile
      context: .
    volumes:
      - type: bind
        source: $PWD
        target: /go/src/app
    networks:
      - backend